plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.jetbrainsKotlinAndroid)

    // Google services Gradle plugin
    id("com.google.gms.google-services")

    alias(libs.plugins.compose.compiler)
}

android {
    namespace 'com.example.mz_focusnews'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.mz_focusnews"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        compose true
        viewBinding true
    }

    composeCompiler {
        reportsDestination = layout.buildDirectory.dir("compose_compiler")
        stabilityConfigurationFile = rootProject.layout.projectDirectory.file("stability_config.conf")
    }

    packaging {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }

    dependencies {
        implementation libs.appcompat
        implementation libs.material
        implementation libs.activity
        implementation libs.constraintlayout
        implementation libs.lifecycle.runtime.ktx
        implementation libs.activity.compose
        implementation platform(libs.compose.bom)
        implementation libs.ui
        implementation libs.ui.graphics
        implementation libs.ui.tooling.preview
        implementation libs.material3
//        implementation("androidx.navigation:navigation-fragment-ktx:2.7.7")
//        implementation("androidx.navigation:navigation-ui-ktx:2.7.7")

        testImplementation libs.junit
        androidTestImplementation libs.ext.junit
        androidTestImplementation libs.espresso.core


        implementation 'com.google.code.gson:gson:2.10.1'               // 2.8.6?
        implementation 'com.github.bumptech.glide:glide:4.12.0'
        annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'

        // 이미지 로딩을 위한 Glide
        implementation 'com.github.bumptech.glide:glide:4.12.0'
        annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'

        implementation 'org.jsoup:jsoup:1.17.2'
        implementation 'com.google.android.material:material:1.11.0'
        implementation 'androidx.viewpager2:viewpager2:1.1.0'
        implementation 'me.relex:circleindicator:2.1.6'
        implementation 'androidx.recyclerview:recyclerview:1.3.2'

        // MySQL 의존성 추가
        implementation files('libs/mysql-connector-java-5.1.49-bin.jar')

        // 스프링 부트 Retrofit 설정
        implementation 'com.squareup.retrofit2:retrofit:2.11.0'
        implementation 'com.squareup.retrofit2:converter-gson:2.11.0'
        implementation 'com.squareup.okhttp3:logging-interceptor:4.11.0'


        implementation libs.navigation.fragment
        implementation libs.navigation.ui
        androidTestImplementation platform(libs.compose.bom)
        androidTestImplementation libs.ui.test.junit4
        testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'
        testImplementation "org.mockito:mockito-core:3.+"
        debugImplementation libs.ui.tooling
        debugImplementation libs.ui.test.manifest

        // Apache Commons Math
        implementation 'org.apache.commons:commons-math3:3.6.1'

        implementation "androidx.work:work-runtime:2.8.1" // 최신 버전으로 교체하세요

        // glide
        implementation 'com.github.bumptech.glide:glide:4.13.0'
        annotationProcessor 'com.github.bumptech.glide:compiler:4.13.0'

        // material design
        implementation 'androidx.compose.material:material'

        // such as input and measurement/layout
        implementation libs.androidx.ui

        // Android Studio Preview support
        implementation libs.androidx.ui.tooling.preview
        debugImplementation libs.androidx.ui.tooling

        // navigation
        implementation(libs.androidx.navigation.compose)

        implementation("androidx.compose.ui:ui")
        implementation("androidx.compose.ui:ui-graphics")
        implementation("androidx.compose.ui:ui-tooling-preview")
        implementation("androidx.compose.material3:material3")

        // image url
        implementation(libs.coil.compose)

        // custom tab
        implementation("androidx.browser:browser:1.8.0")

        // Firebase
        implementation(platform("com.google.firebase:firebase-bom:33.13.0"))
        implementation("com.google.firebase:firebase-messaging:24.1.1")


    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.androidx.tools.core
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
